/* Full family poster. Source records are already scoped to the signed-in family. */
(function(){
const W=594,H=420, LEFT=21, RIGHT=573, TOP=47, BOTTOM=385;
function safe(s){return String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function makeModel(data){const people=(data.people||[]).filter(p=>p&&p.id).map(p=>({id:String(p.id),name:String(p.full_name||'ללא שם')}));const byId=new Map(people.map(p=>[p.id,p])),edges=new Map(),couples=new Map();for(const e of data.parents||[]){const a=String(e.parent_id),b=String(e.child_id);if(byId.has(a)&&byId.has(b)&&a!==b)edges.set(a+'|'+b,{from:a,to:b})}for(const u of data.unions||[]){const a=String(u.person_a),b=String(u.person_b);if(byId.has(a)&&byId.has(b)&&a!==b){const key=[a,b].sort().join('|');couples.set(key,{a,b,status:u.status==='ended'?'ended':'active'})}}return {people,byId,edges:[...edges.values()],couples:[...couples.values()]}}
function components(m){const a=new Map(m.people.map(p=>[p.id,new Set()]));for(const e of m.edges){a.get(e.from).add(e.to);a.get(e.to).add(e.from)}for(const c of m.couples){a.get(c.a).add(c.b);a.get(c.b).add(c.a)}const done=new Set(),out=[];for(const p of m.people){if(done.has(p.id))continue;const q=[p.id],ids=[];done.add(p.id);while(q.length){let id=q.shift();ids.push(id);for(const v of a.get(id))if(!done.has(v)){done.add(v);q.push(v)}}out.push(ids)}return out.sort((a,b)=>b.length-a.length)}
function layout(m){const result=[];for(let ci=0;ci<components(m).length;ci++){const ids=components(m)[ci],set=new Set(ids),edges=m.edges.filter(e=>set.has(e.from)&&set.has(e.to)),couples=m.couples.filter(c=>set.has(c.a)&&set.has(c.b));const level=new Map(ids.map(id=>[id,0]));/* longest-path relaxation; cyclic parent records remain bounded and visible */
 for(let i=0;i<ids.length;i++){let changed=false;for(const e of edges){const next=Math.min(ids.length,level.get(e.from)+1);if(next>level.get(e.to)){level.set(e.to,next);changed=true}}if(!changed)break}
 /* Keep partners in one row where doing so does not reverse a parent edge. */
 for(let iter=0;iter<ids.length;iter++){let changed=false;for(const c of couples){let a=level.get(c.a),b=level.get(c.b);if(a===b)continue;let low=a<b?c.a:c.b,high=a<b?c.b:c.a;const target=level.get(high);if(!edges.some(e=>e.from===low&&level.get(e.to)<=target)){level.set(low,target);changed=true}}for(const e of edges)if(level.get(e.to)<=level.get(e.from)){level.set(e.to,level.get(e.from)+1);changed=true}if(!changed)break}
 const levels=[...new Set(level.values())].sort((a,b)=>a-b),rows=levels.map(v=>ids.filter(id=>level.get(id)===v).sort((a,b)=>m.byId.get(a).name.localeCompare(m.byId.get(b).name,'he')));const pos=()=>new Map(rows.flatMap(row=>row.map((id,i)=>[id,i])));
 /* Barycentric sweeps make partners and common children neighbors while retaining one card per person. */
 for(let pass=0;pass<12;pass++){let p=pos(),indices=pass%2===0?[...rows.keys()].slice(1):[...rows.keys()].slice(0,-1).reverse();for(const ri of indices){const row=rows[ri],before=new Map(row.map((id,i)=>[id,i]));let points=id=>{let linked=edges.filter(e=>pass%2===0?e.to===id:e.from===id).map(e=>pass%2===0?e.from:e.to).filter(x=>p.has(x));return linked.length?linked.reduce((s,x)=>s+p.get(x),0)/linked.length:before.get(id)};row.sort((a,b)=>{let ba=points(a),bb=points(b);for(let c of couples){if(c.a===a&&row.includes(c.b))ba=(ba+before.get(c.b))/2;if(c.b===a&&row.includes(c.a))ba=(ba+before.get(c.a))/2;if(c.a===b&&row.includes(c.b))bb=(bb+before.get(c.b))/2;if(c.b===b&&row.includes(c.a))bb=(bb+before.get(c.a))/2}return ba-bb||before.get(a)-before.get(b)})}}
 /* Large graphs are split by whole generation rows. Repeat the boundary row on both sheets,
    retaining stable person numbers so the continuation is explicit. */
 const slices=[];let first=0;while(first<rows.length){let end=first,unique=new Set();while(end<rows.length&&end-first<5&&unique.size+rows[end].length<=48&&rows[end].length<=12){rows[end].forEach(x=>unique.add(x));end++}if(end<rows.length&&rows[end].length>12){/* Wide generation tiles include the preceding rows that link to it. */let row=rows[end];for(let start=0;start<row.length;start+=12){let group=row.slice(start,start+12),extra=new Set(group);for(let pass=0;pass<end-first+2;pass++){for(const e of edges)if(extra.has(e.to))extra.add(e.from);for(const c of couples){if(extra.has(c.a))extra.add(c.b);if(extra.has(c.b))extra.add(c.a)}}let tile=rows.slice(first,end+1).map(r=>r.filter(id=>extra.has(id))).filter(r=>r.length);slices.push(tile)}first=end+1;continue}if(end===first){/* Single very wide root generation: tile without losing a person. */let row=rows[first];for(let start=0;start<row.length;start+=12)slices.push([row.slice(start,start+12)]);first++;continue}let slice=rows.slice(first,end);slices.push(slice);first=end===rows.length?end:Math.max(first+1,end-1)}
 for(const slice of slices){const visible=new Set(slice.flat());let includedEdges=edges.filter(e=>visible.has(e.from)&&visible.has(e.to)),includedCouples=couples.filter(c=>visible.has(c.a)&&visible.has(c.b));let count=Math.max(...slice.map(r=>r.length)),cardW=Math.min(48,(RIGHT-LEFT-5*(count-1))/count),cardH=Math.min(22,Math.max(11,270/(slice.length*2.6))),gapX=Math.max(2,Math.min(12,(RIGHT-LEFT-count*cardW)/(count+1))),rowGap=(BOTTOM-TOP-cardH*slice.length)/Math.max(1,slice.length-1),nodes=[];
 slice.forEach((row,r)=>{let span=row.length*cardW+(row.length-1)*gapX,x0=(W-span)/2,y=TOP+r*rowGap;row.forEach((id,j)=>nodes.push({id,x:x0+j*(cardW+gapX),y,w:cardW,h:cardH,row:r}))});
 result.push({component:ci+1,part:slices.length,rows:slice,nodes,edges:includedEdges,couples:includedCouples,allEdges:edges.length,allPeople:ids.length})}
 }return result}
function svg(m,page,index,total){const map=new Map(page.nodes.map(n=>[n.id,n])),families=new Map(),paths=[],tag=id=>String(m.people.findIndex(p=>p.id===id)+1).padStart(3,'0');for(const e of page.edges){let key=page.edges.filter(t=>t.to===e.to).map(t=>t.from).sort().join('|')+'@'+map.get(e.to).row;let family=families.get(key)||{parents:key.split('@')[0].split('|'),children:new Set()};family.children.add(e.to);families.set(key,family)}
 for(const c of page.couples){let a=map.get(c.a),b=map.get(c.b);if(!a||!b)continue;let line;if(a.row===b.row){let left=a.x<b.x?a:b,right=left===a?b:a;line=`M${left.x+left.w} ${left.y+left.h/2}H${right.x}`}else{let x=a.x+a.w/2,xx=b.x+b.w/2,mid=(a.y+a.h+b.y)/2;line=`M${x} ${a.y+a.h}V${mid}H${xx}V${b.y}`}paths.push(`<path d="${line}" fill="none" stroke="#b78a28" stroke-width=".85" ${c.status==='ended'?'stroke-dasharray="2 1.4"':''}/>`);if(c.status==='ended')paths.push(`<text x="${(a.x+b.x)/2}" y="${Math.min(a.y,b.y)-2}" font-size="3.2" text-anchor="middle" fill="#85621b">לשעבר</text>`)}
 let lane=0;for(const f of families.values()){const ps=f.parents.map(id=>map.get(id)).filter(Boolean),kids=[...f.children].map(id=>map.get(id)).filter(Boolean);if(!ps.length||!kids.length)continue;let parentBottom=Math.max(...ps.map(n=>n.y+n.h)),childTop=Math.min(...kids.map(n=>n.y)),bus=parentBottom+(childTop-parentBottom)*(0.38+0.08*(lane++%3));if(kids[0].row-Math.max(...ps.map(n=>n.row))>1){let rail=Math.max(...page.nodes.map(n=>n.x+n.w))+5+3*(lane%4),entry=parentBottom+5,exit=childTop-5;for(const n of ps){let x=n.x+n.w/2;paths.push(`<path d="M${x} ${n.y+n.h}V${entry}H${rail}" stroke="#438764" stroke-width=".7" fill="none"/>`)}paths.push(`<path d="M${rail} ${entry}V${exit}" stroke="#438764" stroke-width=".7" fill="none"/>`);for(const n of kids){let x=n.x+n.w/2;paths.push(`<path d="M${rail} ${exit}H${x}V${n.y}" stroke="#438764" stroke-width=".7" fill="none"/>`)}continue}let xx=[...ps,...kids].map(n=>n.x+n.w/2),lo=Math.min(...xx),hi=Math.max(...xx);paths.push(`<path d="M${lo} ${bus}H${hi}" stroke="#438764" stroke-width=".7" fill="none"/>`);for(const n of ps)paths.push(`<path d="M${n.x+n.w/2} ${n.y+n.h}V${bus}" stroke="#438764" stroke-width=".7" fill="none"/>`);for(const n of kids)paths.push(`<path d="M${n.x+n.w/2} ${bus}V${n.y}" stroke="#438764" stroke-width=".7" fill="none"/>`)}
 /* Edges between nonadjacent ranks and cyclic records remain individually traceable. */
 const covered=new Set([...families.values()].flatMap(f=>f.parents.flatMap(a=>[...f.children].map(b=>a+'|'+b))));for(const e of page.edges)if(!covered.has(e.from+'|'+e.to)){let a=map.get(e.from),b=map.get(e.to),x=a.x+a.w/2,xx=b.x+b.w/2,yy=(a.y+a.h+b.y)/2;paths.push(`<path d="M${x} ${a.y+a.h}V${yy}H${xx}V${b.y}" stroke="#438764" stroke-width=".7" fill="none"/>`)}
 const cards=page.nodes.map(n=>`<g><rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="2.8" fill="#fffefa" stroke="#9dbca7" stroke-width=".65"/><foreignObject x="${n.x+1}" y="${n.y+1}" width="${n.w-2}" height="${n.h-2}"><div xmlns="http://www.w3.org/1999/xhtml" dir="rtl" style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;text-align:center;color:#153e2e;font:700 ${m.byId.get(n.id).name.length>32?3.1:Math.min(5.7,Math.max(3.2,n.h*.31))}px Arial,sans-serif;line-height:1.1;overflow:hidden;overflow-wrap:anywhere;word-break:break-word">${safe(m.byId.get(n.id).name)}${total>1?`<small style="font:2.4px Arial;color:#7d9281"> #${tag(n.id)}</small>`:''}</div></foreignObject></g>`).join('');let footer=`${m.people.length} אנשים · ${m.edges.length} קשרי הורות · ${m.couples.length} זוגיויות`;let continuation=total>1?` · עמוד ${index+1} מתוך ${total} · מספרי אדם זהים מציינים רשומה זהה בדפי המשך`:'';
 return `<svg xmlns="http://www.w3.org/2000/svg" width="594mm" height="420mm" viewBox="0 0 594 420"><rect width="594" height="420" fill="#f8f6ef"/><text x="573" y="23" text-anchor="end" font-size="11" font-family="Arial" font-weight="700" fill="#153e2e">שושלת · כולם מחוברים</text><text x="21" y="23" font-size="5" font-family="Arial" fill="#5a7463">פוסטר A2 לרוחב${continuation}</text><path d="M21 32H573" stroke="#ba9132" stroke-width=".65"/>${paths.join('')}${cards}<path d="M21 396H573" stroke="#ba9132" stroke-width=".45"/><text x="573" y="407" text-anchor="end" font-size="4.5" font-family="Arial" fill="#51705b">ירוק: הורה-ילד · זהב: זוגיות · זהב מקווקו: לשעבר</text><text x="21" y="407" font-size="4.5" font-family="Arial" fill="#51705b">${footer}</text></svg>`}
async function build(data){const model=makeModel(data),pages=layout(model);if(!pages.length)throw Error('אין אנשים להדפסה');const {jsPDF}=window.jspdf||{};if(!jsPDF)throw Error('מנוע PDF לא זמין');let pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a2',compress:true}),preview=[];for(let i=0;i<pages.length;i++){if(i)pdf.addPage('a2','landscape');let xml=svg(model,pages[i],i,pages.length),img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(xml);await img.decode();let canvas=document.createElement('canvas');canvas.width=3508;canvas.height=2480;let ctx=canvas.getContext('2d');ctx.fillStyle='#f8f6ef';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,W,H);preview.push({component:pages[i].component,part:i+1,people:pages[i].nodes.map(n=>n.id),parentEdges:pages[i].edges.length,couples:pages[i].couples.length})}return {pdf,preview,model}}
window.ShTreeExport={build,makeModel,layout,svg};
})();
